[build]
builder = "nixpacks"
buildCommand = "npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envVars]
PROJECT_ROOT = "/app"
