[build]
builder = "nixpacks"
buildCommand = "npm run build && cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envVars]
PROJECT_ROOT = "/app"
