[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "PROJECT_ROOT=/app npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
